### ISSUE TITLE
can't convert null to object

### ISSUE THREAD

**Issue by mmuncan1980** [Isopolito/gNordVPN-Local#31] opened 2022-09-19 09:25 UTC
i have tried several times to reinstall, system is fully up-to-date, Kali at the moment.

when i click on "on" it then says: "can't convert null to object" and doesnt start instead shows this error message.i dont know why this happens. please help! :D

**Comment by Isopolito** [comment] 2022-09-20 12:11
Hi @mmuncan1980, I'll load up a Kali VM and investigate. What version of gnome are you using?

**Comment by Tructruc** [comment] 2022-10-09 19:45
I have the same problem on pop os

**Comment by Isopolito** [comment] 2022-10-09 19:57
@Tructruc what version of pop os and gnome are you running?

**Comment by Tructruc** [comment] 2022-10-09 20:10
> @Tructruc what version of pop os and gnome are you running?

Pop os 22.04, gnome 42.2

**Comment by Isopolito** [comment] 2022-10-09 20:22
Interesting, Pop Os is my daily driver and I haven't seen that problem with those versions. I'll try to replicate it this week and get a fix out there. You installed it from the gnome extensions site?

**Comment by ArthurMitchell42** [comment] 2022-10-15 10:58
I'm also getting this and some other startup problems:

TypeError: can't convert null to object

Stack trace:
  buildPrefsWidget@/home/arthurm/.local/share/gnome-shell/extensions/gnordvpn-local@isopolito/prefs.js:105:33
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by Isopolito** [comment] 2022-10-15 13:32
Hi @ArthurMitchell42 , the stack trace will be helpful thanks! Right now though I'm still trying to replicate this issue. Can you tell me:
1. What version of the plugin you're using?
2. Did you install from the gnome extensions site?
3. What version of gnome are you are running?
4. What OS and version number of it you're using?

I'll get it fixed once I can replicate.Appreciate it!

**Comment by Isopolito** [comment] 2022-10-15 13:59
More questions....What's going on when the error occurs? For instance, do you happen to _not_ have an internet connection when the error shows up?

**Comment by ArthurMitchell42** [comment] 2022-10-15 20:42
![image](https://user-images.githubusercontent.com/82239494/196006498-ccf70306-332c-4d1b-b0b0-dbe5ed9d9e95.png)
Hi,
I'm using the one on gnome extension, I think it's 11? I've attached a shot.
This is running on Ubuntu 22.04 LTS using Wayland and gnome 42.4

The extension was working well but now this happens after boot and the internet/network is connected. I can't trace to an indecent when the failure started but I got an update on Thursday and it might have been after that. I did have occasion issues with other errors before mind you.
I've also tried reboots, log out & in. I also removed it and reinstalled from the extension page using the browser plug in as usual and it still has the same error.
I'm happy to provide any more investigation if you need.
Arthur

**Comment by Isopolito** [comment] 2022-10-16 14:02
Thanks very much @ArthurMitchell42, I'll get a VM set up to match what you have and see if I can replicate it.

**Comment by ArthurMitchell42** [comment] 2022-10-16 19:58
Thanks, let me know if you need me to do anything from my end.

**Comment by ArthurMitchell42** [comment] 2022-10-26 13:14
Hi, do you need any further investigation work please? Is there any light at the end of the tunnel?
Regards, A

**Comment by Isopolito** [comment] 2022-10-26 15:44
Hi @ArthurMitchell42, I was unable to replicate this and have been slammed at work so haven't been able to circle back to it. If I could reproduce this issue I would able to fix it...One thing you can try is to manually remove it and reinstall it. This document outlines how to do it: https://www.debugpoint.com/manual-installation-gnome-extension/

Just remember to delete the existing gnordvpn folder that's installed first. You can download the zip file from gnome extension site, you'll want the one for version gnome 42: 
![image](https://user-images.githubusercontent.com/13524742/198072396-89207303-9224-4a27-acf8-23bb0e19c0fa.png)

Please let me know how that goes, apologies for any inconvenience you're having. It's important to me to get these issues resolved.

**Comment by ArthurMitchell42** [comment] 2022-10-30 18:19
Hi there, well the good news is it's working now, the part I can't explain is why. I've been through uninstalling and re-installing, also trying the ZIP from GitHub directly. No luck. I checked the NordVPN just to make sure it was ok and it confirmed I was logged in and it then connected fine. Just out of curiosity/desperation I re-installed the NordVPN from the .deb (despite it still working) and it all sprang back into life. I can't explain what was resolved but something was obviously missing/corrupt and now is fixed. Sorry to have bothered you but I can't explain this at all. :)

**Comment by Isopolito** [comment] 2022-10-31 15:26
Hi @ArthurMitchell42, it was no bother at all. I'm just glad it's working for you now. In fact, you reminded me that there is an outstanding issue I intend to fix. I want to investigate it a bit more and then make an issue for it. But essentially I've seen the extension crash and burn when NordVPN is not working or is not installed. The extension should gracefully handle that situation but currently doesn't.

@mmuncan1980 and @Tructruc: by chance is there a problem with your nordVPN (or is it not installed) when are you having the issues you reported?

**Comment by Jesse-Millwood** [comment] 2022-11-07 16:56
for what it's worth, I just signed up for nord VPN today and installed the deb today. I'm on Pop OS and have the same issue as @ArthurMitchell42

**Comment by Isopolito** [comment] 2022-11-07 17:18
@Jesse-Millwood, the issue being trying to use the extension before NordVPN is up and running properly?

**Comment by Jesse-Millwood** [comment] 2022-11-07 18:54
> @Jesse-Millwood, the issue being trying to use the extension before NordVPN is up and running properly?

I logged in via the command line using the token and used the command line tool to connect. I did verify that I was connected with some websites that showed that the VPN was working

**Comment by Isopolito** [comment] 2022-11-07 19:09
@Jesse-Millwood Ok so even with the active vpn connection you're still getting that "can't convert null to object" error?

**Comment by Jesse-Millwood** [comment] 2022-11-07 19:20
> @Jesse-Millwood Ok so even with the active vpn connection you're still getting that "can't convert null to object" error?

That's correct. I uninstalled the plugin through the gnome extensions site. Then I disconnected and reconnected to nord VPN through the command line utility. I then tried to install the plug-in again and received the same error message.

**Comment by Isopolito** [comment] 2022-11-07 19:24
@Jesse-Millwood Thanks

**Comment by Jesse-Millwood** [comment] 2022-11-07 20:01
@Isopolito I actually restarted my computer and the extension seems to be working now!

**Comment by Isopolito** [comment] 2022-11-08 13:00
@Jesse-Millwood Weird lol. Glad it's working now for you though. Eventually I'll get to the bottom of this. Thanks for your input, it all helps me circle closer to the problem

**Comment by ArthurMitchell42** [comment] 2022-11-08 21:04
Hmmm, I'm not at all sure what's happening. I rebooted today and although the extension seems to be working the extension manager shows this:
![nordvpn_error](https://user-images.githubusercontent.com/82239494/200674943-40b43847-37ea-4670-b4c4-940b283ff413.png)
If I click settings it doesn't give me a stack trace but opens the settings as normal?

**Comment by Isopolito** [comment] 2022-11-08 21:46
Hi @ArthurMitchell42, that's a known issue that is fixed in the newest version (for gnome 43). It doesn't actually cause any problems, other then you can't disable the extension  :)

**Comment by ArthurMitchell42** [comment] 2022-11-08 23:25
That's good, I'll ignore it thanks

**Comment by Isopolito** [comment] 2022-12-04 20:05
Releasing a new version that will address these issues today, thanks for the feedback everyone!

**Closed by Isopolito** 2022-12-04 20:05 UTC
